blueprint:
  name: Zigbee2MQTT - Sonoff SNZB-01 Zigbee Wireless Switch
  author: Sakrapher
  description: >
    Automate your Sonoff SNZB-01 Zigbee Wireless Switch via Zigbee2MQTT.
    Inspired by https://github.com/AramidX/ha-blueprint/blob/main/blueprints/sonoff/sonoff_snzb01_wireless_switch_z2m.yaml
  domain: automation
  input:
    switch:
      name: Sonoff SNZB-01 Zigbee Wireless Switch
      description: Sonoff SNZB-01 Zigbee Wireless Switch to use
      selector:
        entity:
          integration: mqtt
          domain:
          - sensor
          multiple: false
    single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long Press
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
  source_url: https://github.com/Sakrapher/HA-Blueprints/edit/main/Z2M_Sonoff-SNZB-01-Wireless-Switch.yaml
mode: parallel
max_exceeded: silent
max: 10
trigger:
- platform: state
  entity_id: !input switch
  attribute: action
action:
- variables:
    command: '{{ trigger.to_state.state }}'
- choose:
  - conditions:
    - '{{ command == ''single'' }}'
    sequence: !input single_press
  - conditions:
    - '{{ command == ''double'' }}'
    sequence: !input double_press
  - conditions:
    - '{{ command == ''long'' }}'
    sequence: !input long_press
